create table if not exists public.signatures (
  id bigint generated by default as identity primary key,
  agrees text not null check (agrees in ('yes', 'no')),
  name text not null,
  country text not null,
  email text not null,
  comments text default '',
  created_at timestamptz not null default now()
);

create index if not exists signatures_created_at_idx on public.signatures (created_at desc);

-- Optional: if you want to allow public insert access through the client, add a policy.
-- For this app, the server-side service role key bypasses RLS, so this is not required.
